=== gpmacareno/XML-XSD-DTD/Tema 4/Tema4XSD/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="editorial" type="xs:string"/>
                            <xs:element name="descripcion">  
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="200"></xs:maxLength>
                                        <xs:whiteSpace value="collapse"/>
                                    </xs:restriction>
                                </xs:simpleType>  
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>


<!-- <!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, autores, editorial, descripcion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT
editorial (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>-->

<!-- <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> en vez de xs podemos poner el prefijo 
que queramos pero siempre debemos utilizar  ese en todo el documento-->

=== gpmacareno/XML-XSD-DTD/Tema 4/Tema4XSD/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<libros
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./Ejercicio5.xsd">


    <libro>
        <titulo>El Quijote</titulo>
        <autores>
            <autor>Miguel de Cervantes</autor>
        </autores>
        <editorial>Anaya</editorial>
        <descripcion>Burlas de las novelas de caballería</descripcion>
    </libro>
    <libro>
        <titulo>Buenos Presagios</titulo>
        <autores>
            <autor>Neil Gaiman</autor>
            <autor>Terry Pratchett</autor>
        </autores>
        <editorial>McGraw Hill</editorial>
        <descripcion>Comedia de tono irónico sobre el anticristo</descripcion>
    </libro>

</libros>
